# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'failure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt


class Ui_Failure(object):
    def __init__(self):
        """
        Encapsulation method according to each failed operation occurred for each function.
        """
        self.text = ""
    def setupUi(self, Dialog):
        """
        SetupUi for failure operation
        :param Dialog: static object
        :return:
        """
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(332, 57)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setGeometry(QtCore.QRect(20, 20, 281, 20))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Failure"))
        self.label.setText(_translate("Dialog", self.text))


if __name__ == "__main__":
    """
    Failure program GUI
    """
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Failure()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
